version: "3.9"
services:
  backend:
    build: .
    volumes:
      - ./schooldef:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=SchoolDef2
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: SchoolDef2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
